services:
  chainlit_frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    container_name: chainlit_frontend
    restart: always
    ports:
      - "8501:8501"
    expose:
      - 8501
    volumes:
      - .:/app/frontend
      - ./.chainlit:/app/frontend/.chainlit
      - ./public:/app/frontend/public
    env_file:
      - .env
    environment:
      - BACKEND_URL=${BACKEND_URL}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID}
      - OAUTH_GITHUB_CLIENT_SECRET=${OAUTH_GITHUB_CLIENT_SECRET}
      - CHAINLIT_HOST=0.0.0.0
      - CHAINLIT_PORT=8501
      - DATABASE_URL=postgresql+asyncpg://postgresadmin:postgresadmin@postgres_db:5432/medical_rag_db
    networks:
      - medical_rag_network

networks:
  medical_rag_network:
    external: true
